export const SET_INCREDIBLE_OFFERS = "SET_INCREDIBLE_OFFERS"
export const ADD_INCREDIBLE_OFFERS = "ADD_INCREDIBLE_OFFERS";
export const SET_LOADING_INCREDIBLE_OFFERS = "SET_LOADING_INCREDIBLE_OFFERS"
export const SET_ERROR_INCREDIBLE_OFFERS = "SET_ERROR_INCREDIBLE_OFFERS"
