export const SET_INCREDIBLE_OFFERS = "SET_INCREDIBLE_OFFERS"
export const ADD_INCREDIBLE_OFFERS = "ADD_INCREDIBLE_OFFERS";
export const SET_LOADING = "SET_LOADING"
export const SET_ERROR = "SET_ERROR"
